package numberguesser;

import java.util.Random;

/**
 *
 * @author Sean Ennis
 */
public class NumberGuesser extends javax.swing.JFrame {

//    private Random random = new Random();
    //private NumberGuessService ns;
    private final int MIN_GUESS = 1;
    private final int MAX_GUESS = 10;
    private int randNumber;
    private int attempts = 0;
    private int wins = 0;
    private int guess = 0;

    /**
     * Creates new form NumberGuesser
     */
    public NumberGuesser() {
        initComponents();
        //this.ns = ns;
        this.lblGuessRange.setText("Enter a guess between " + MIN_GUESS + " and " + MAX_GUESS + ", inclusive");
        generateRandomInteger(MIN_GUESS, MAX_GUESS, randNumber);
    }

    private void generateRandomInteger(int aMinGuess, int aMaxGuess, int randNumber) {
        if (aMinGuess > aMaxGuess) {
            throw new IllegalArgumentException("Start cannot exceed End.");
        }

//        this.randNumber = (int)Math.random() * this.MAX_GUESS + MIN_GUESS;
//        System.out.println("Generated : " + randNumber);
//        this.randNumber = random.nextInt(this.MAX_GUESS) + this.MIN_GUESS;
        this.randNumber = this.MIN_GUESS + (int) (Math.random() * ((this.MAX_GUESS - this.MIN_GUESS) + 1));
        System.out.println("Number Generated : " + this.randNumber);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGuessRange = new javax.swing.JLabel();
        lblEnterGuess = new javax.swing.JLabel();
        txtGuess = new javax.swing.JTextField();
        btnGuess = new javax.swing.JButton();
        lblAttempts = new javax.swing.JLabel();
        lblWins = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Number Guesser");

        lblGuessRange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblEnterGuess.setText("Enter Guess Below");

        btnGuess.setText("Guess");
        btnGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessActionPerformed(evt);
            }
        });

        lblAttempts.setText("Attempts: 0");

        lblWins.setText("Wins : 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGuessRange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnterGuess)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGuess)
                                    .addComponent(txtGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 85, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblAttempts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWins)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGuessRange, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEnterGuess)
                .addGap(11, 11, 11)
                .addComponent(txtGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAttempts)
                    .addComponent(lblWins))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessActionPerformed
        this.guess = Integer.parseInt(txtGuess.getText());
        
        if (this.guess < this.MIN_GUESS || this.guess > this.MAX_GUESS) {
            System.out.println("Please enter a number within the given range");
        } else {
        if (this.guess > this.randNumber) {
            System.out.println("Try a lower number.");
            this.attempts += 1;
            this.lblAttempts.setText("Attempts : " + this.attempts);
        }
        if (this.guess < this.randNumber) {
            System.out.println("Try a higher number.");
            this.attempts += 1;
            this.lblAttempts.setText("Attempts : " + this.attempts);
        }
        if (this.guess == this.randNumber) {
            System.out.println("You Guessed Right!");
            this.attempts += 1;
            this.wins += 1;
            this.lblWins.setText("Wins : " + this.wins);
            this.lblAttempts.setText("Attempts : " + this.attempts);
            generateRandomInteger(MIN_GUESS, MAX_GUESS, randNumber);
            this.txtGuess.setText("");
            this.txtGuess.requestFocus();
        }
        }
        //String input = this.txtGuess.getText();
        //NumberGuessResult result = ns.checkGuess(input);
        //switch(result) {
         //   case LOW:
        //this.txtMsg.setText("Too low, try again.")
        //break;
        //case HIGH:
        //this.txtMsg.setText("Too high, try again.")
        //break;
        //default:
        //this.txtMsg.setText("Correct!")
        //break;
        //}
    }//GEN-LAST:event_btnGuessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumberGuesser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumberGuesser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumberGuesser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumberGuesser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumberGuesser().setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuess;
    private javax.swing.JLabel lblAttempts;
    private javax.swing.JLabel lblEnterGuess;
    private javax.swing.JLabel lblGuessRange;
    private javax.swing.JLabel lblWins;
    private javax.swing.JTextField txtGuess;
    // End of variables declaration//GEN-END:variables
}
